% -------------------------------------------------------------------
%  Generated by MATLAB on 6-Mar-2018 21:38:19
%  MATLAB version: 8.3.0.532 (R2014a)
% -------------------------------------------------------------------
saveVarsMat = load('x1_step1_gain_DATA.mat');

x1_step1_gain = saveVarsMat.x1_step1_gain; % <4800x1 double> ÔªËØÌ«¶à

clear saveVarsMat;
